### ISSUE TITLE
Copy information about conferences over

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/web#1]
- [x] FEniCS 2021
- [x] FEniCS 2019
- [x] FEniCS 2018
- [x] FEniCS 2017
- [ ] Pictures from older conferences, currently at https://fenicsproject.org/pub/photos/

**Comment by michalhabera** [comment]
Would be nice to retain these gems, https://fenicsproject.org/pub/photos/

**Comment by mscroggs** [comment]
Looks like that page is currently outside wordpress, so will probably continue to exist as it is, but it's a good idea to copy it over to make sure the pictures aren't lost

**Comment by mscroggs** [comment]
The photos at https://fenicsproject.org/pub/photos/ are 1.5GB so probably shouldn't be hosted on github. I've downloaded them all to my external hard drive so a have a copy just in case they get lost when we switch over
