### ISSUE TITLE
Host website in GitHub pages

### ISSUE THREAD

**Issue by datapythonista** [FEniCS/web#108]
We (NumFOCUS) are moving out of Rackspace, where you've got your website hosted. Rackspace offered long time ago the servers for free, but the sponsorship finished couple of years ago. Now Rackspace is very overpriced, and the service is very poor (e.g. we need to call their support to stop a server, we can't do it from their dashboard, no way to access the servers with the organization credentials...).

We're finalizing a new agreement for free hosting, but for what I saw, your website could probably be better hosted with GitHub pages. This is the preferred option for static websites that don't exceed their quota. You can read more here: https://github.com/numfocus/infrastructure/blob/master/projects/README.md#small-static-site

Please let me know if this makes sense to you, and if it does, if you can move the website. Thanks!

**Comment by mscroggs** [comment]
We initially had this hosted on github pages, but we had difficulty setting up pages like https://docs.fenicsproject.org. I'm sure it can be done though, so I'll look into it

**Comment by mscroggs** [comment]
Do you know when the Rackspace will be deactivated (ie what's my deadline for moving this to github pages?)

**Comment by mscroggs** [comment]
It's fixed! Thank for reporting this bug

**Comment by datapythonista** [comment]
It's very easy to set up a custom domain for GitHub pages. You just need to add a CNAME for you dns, and go to Settings / Pages and you have a Custom domain box where you write the domain.

The main difference is that instead of using rsync, you'll be using git to add and delete things and the history will be kept.

If storage or anything else is a problem, then NumFOCUS will have soon available bigger static hosting, and we could quickly move things there (with rsync again).

I'm shutting down most rackspace servers today, I just have fenics and pandas left, so would be nice if we could have it in one or two weeks. Or if you create the repo for github pages and give me admin access, I can help you with it, and leave most things working between today and tomorrow.

**Comment by mscroggs** [comment]
@jhale @chrisrichardson I think I've worked out how to sensibly move all the various pieces of the FEniCS website to GitHub pages, but I'll need your help setting up repos/DNS/etc

**Comment by datapythonista** [comment]
I have access to change the fenicsproject.org DNS when you're ready, just ping me. I also have access to fenicsproject.online, which doesn't seem to be used, but I guess your project requested. If creatinng the repo in your organization is not immediate and you want in the pydata organization for now, I can create it for you, and we can transfer it later.

**Comment by datapythonista** [comment]
We'll be closing the NumFOCUS rackspace account next week. Not sure if there has been any work on this, but hopefully it's completed by then, so the website can continue to work after the old server is shut down. At least make sure that you save anything in that server that you don't have anywhere else.

If you need anything from me, just ping me.

**Comment by chrisrichardson** [comment]
@jhale @mscroggs - this seems urgent

**Comment by jhale** [comment]
I don't remember asking for `fenicsproject.online`! But if you have it, I guess it could be useful in the future.

My understanding is that we are already running fenicsproject.org via GitHub pages so we don't need any further assistance there, except duplication of the current DNS records.

What we do need is somewhere to store and host (potentially large) static files, e.g. something like Amazon S3?

**Comment by mscroggs** [comment]
> My understanding is that we are already running fenicsproject.org via GitHub pages so we don't need any further assistance there, except duplication of the current DNS records.

No, we changed it to copy the built files to Rackspace when pages such as olddocs were broken. I'll make time this week to sort out moving back to github pages

**Comment by mscroggs** [comment]
Parts of the website that need moving (feel free to edit this comment to add any I've missed):

- [ ] https://fenicsproject.org (ie this repo)
- [ ] https://docs.fenicsproject.org
- [ ] https://fenicsproject.org/olddocs/

**Comment by jhale** [comment]
@mscroggs You are indeed right, thanks for the clarification.

I don't have a great solution for pub and olddocs that keeps them at the current URLs. Particularly in the case of `pub/` we break the GitHub pages and GitHub repository file size recommendations (it's not meant for large file serving).

**Comment by datapythonista** [comment]
I think the recommendations are because in general it's not a great idea to have very big files with git, aince git manages changes, and diffs of 1gb files are mostly useless. But for github pages doesn't seem relevant.

If your whole site is under 1gb and you don't have files bigger than 100mb, I'd move forward with github pages. And if there is any problem, I'm happy to help you find better options

**Comment by jhale** [comment]
We're happy to use GitHub pages for most of the site, but have part of the site `pub` which is 8GB with files larger than 100MB.

For this part we need a better option, preferably something like Amazon S3 (i.e. bucket storage with the option to turn on https access).

**Comment by datapythonista** [comment]
> We're happy to use GitHub pages for most of the site, but have part of the site `pub` which is 8GB with files larger than 100MB.
> 
> For this part we need a better option, preferably something like Amazon S3 (i.e. bucket storage with the option to turn on https access).

I see, I download your website with `wget -r` and I didn't see this, but looks like it didn't download the whole thing. I'll be contacting you shortly with details so you can move the website to the new NumFOCUS infrastructure.

**Comment by jorgensd** [comment]
@mscroggs @jhale what should we do here? Are we ready to close this?

**Comment by mscroggs** [comment]
I think we're ready to switch over, just need to update the DNS so it points to GitHub

**Comment by mscroggs** [comment]
feels very good the finally be closing this!
