### ISSUE TITLE
Warning about certificate

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/web#124]
If you go to https://www.fenicsproject.org, you get a certificate error. but not at https://fenicsproject.org (without the www.)

**Comment by francesco-ballarin** [comment]
This can probably be closed, it seems that now the url with www redirects to the one without www.

**Comment by luzpaz** [comment]
This is still an issue 
![Screenshot_20241110_171709](https://github.com/user-attachments/assets/17cf6619-696a-43cd-96ca-dc8da4c3d716)

**Comment by mscroggs** [comment]
this should be resolved now that we've move to github pages

**Comment by luzpaz** [comment]
Confirmed fix. Thanks!
