### ISSUE TITLE
The dcoumentation labyrinth starting at dolfin.cpp.mesh.Cone

### ISSUE THREAD

**Issue by jabowery** [FEniCS/web#194]
Please fix the C++ method documentation pages to _directly link_ to where one can install the C++ library and header files with the full complement of methods.

I wanted to create a Cone mesh using dolfin, and a site:fenicsproject.org search for "Cone" brought me to:

https://fenicsproject.org/olddocs/dolfin/1.3.0/python/programmers-reference/cpp/mesh/Cone.html

However, because the python interface doesn't provide the Cone method (among a vast array of other methods) I was left wondering how to drop down to C++ to get access to the vast array of methods that python doesn't provide.  This, in turn, left me in the situation where the current work on providing a python interface to dolfin so occupies the documentation space and web searches that I was unable to figure out how to install the dolfin C++ library and header files.  After a few hours I've given up.

**Comment by jorgensd** [comment]
You are looking at a very outdated version of DOLFIN (v1.3.0 was released 2014-01-07).

We are keeping the old documentation for the sake of consistency, but all development and maintenance is done for DOLFINx, ref: https://fenicsproject.discourse.group/t/the-new-dolfinx-solver-is-now-recommended-over-dolfin/8249?u=dokken

The downloading instructions for DOLFINx is stated at: https://fenicsproject.org/download/

For instance, in the modern version of the FEniCS project, we do not provide our own mesh generator (as we believe the that the people spending their life doing mesh generation knows better than us). 
Thus we provide an easy interface to for instance GMSH: 
https://docs.fenicsproject.org/dolfinx/v0.9.0/python/demos/demo_gmsh.html

For instance, you can use GMSH in the following way:
```python
from mpi4py import MPI
import dolfinx

import gmsh

gmsh.initialize()
cone = gmsh.model.occ.addCone(1, 0, 0, 1, 0, 0, 0.5, 0.1)
gmsh.model.occ.synchronize()
gmsh.model.addPhysicalGroup(3, [cone], 1)
gmsh.model.mesh.generate(3)

mesh, cell_tags, facet_tags = dolfinx.io.gmshio.model_to_mesh(
    gmsh.model, MPI.COMM_WORLD, 0, gdim=3
)
gmsh.finalize()

import pyvista

ugrid = pyvista.UnstructuredGrid(*dolfinx.plot.vtk_mesh(mesh))
plotter = pyvista.Plotter()
plotter.add_mesh(ugrid, show_edges=True)
plotter.show()
```
![image](https://github.com/user-attachments/assets/6a85bcea-ff28-4d4c-9f53-7ea06db89669)

I've created the above plot with the following `environment.yml`
```yml
name: fenicsx-test
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx
  - python-gmsh
  - trame-client
  - trame-vtk
  - trame-server
  - trame-vuetify
  - trame
  - ipywidgets
  - pyvista
```
with `conda env create -f environment.yml` and `conda activate fenicsx-test`
and running the script above with `python3 name_of_script.py`.
