### ISSUE TITLE
Complete the list of FEniCS conferences

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/web#4]
The list (currently) at https://fenicsproject.org/conference has gaps in ~2013~, ~2010~, and 2007.

There may also have been pre-2005 conferences?

**Comment by mscroggs** [comment]
Perhaps @garth-wells or @chrisrichardson can help with this?

**Comment by michalhabera** [comment]
FEniCS 2013 was in Cambridge according to some slides available, https://fenicsproject.org/pub/workshops/fenics13/slides/Rhebergen.pdf

**Comment by chrisrichardson** [comment]
I don't know before 2013

**Comment by chrisrichardson** [comment]
I think @meg-simula mentioned that 2010 was held at KTH?

**Comment by jorgensd** [comment]
@mscroggs I guess this is as complete as can be atm?
