### ISSUE TITLE
Replace <a href> links with markdown

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/web#5]
On some copied pages, the links all use `<a href="url">name</a>` syntax. The neater `[name](url)` syntax should be used instead.

This needs changing for:
- [x] The FEniCS 18 page (https://github.com/FEniCS/web/blob/main/fenics18/index.md)
- [x] The FEniCS 17 page (https://github.com/FEniCS/web/blob/main/fenics17/index.md)
- [x] GSoC 2017 (https://github.com/FEniCS/web/blob/main/google-summer-of-code-2017/index.md)
- [x] GSoC 2018 (https://github.com/FEniCS/web/blob/main/google-summer-of-code-2018/index.md)

**Comment by davidchengl74** [comment]
I think I might be able to help to change the href to markdown. 
Is it all you need, changing all links to markdown syntax? 
I am doing this for a school assignment, once I do the pull requests, will you be able to review and merge the pull request? 
The PR needs to be merged for me to obtain full points for this assignment. 
Can you kindly let me know if this could be assigned to me? thanks mate.

**Comment by mscroggs** [comment]
That would be great.

Yes, all this needs is syntax changing from html to markdown.

I'll take a look at your PR once you open it.

**Comment by davidchengl74** [comment]
Hello, can you kindly check if RP #16 and # 17 are okay? 
If anything, your feedback is much appreciated and could #16 be merged?

**Comment by davidchengl74** [comment]
Hello, I updated the GSoC 2017 and GSoC 2018 with RP#18 and RP#19 
Your feedback is much appreciated, and if everything okay, can these two also be merged?

**Comment by mscroggs** [comment]
Syntax is all updated now. Thanks @davidchengl74
